server:
  port: 8084

spring:
  application:
    name: Rabbitmq-Confirms-Producer
  rabbitmq:
    host: 192.168.204.122
    port: 5672
    username: admin
    password: 123456789
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 把消息确认模式改为手动模式
logging:
  level:
    com.rts.mq: info