server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: tPay_routh1                  # 路由的ID(类似Mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service       # 匹配后提供服务的路由地址
          predicates:
            - Path=/tPay/gateway/get/**,/tPay/gateway/info/**  # 断言，路径相匹配的进行路由
#            - After=2024-05-20T21:39:01.047418100+08:00[Asia/Shanghai]
            - Between=2024-05-20T21:39:01.047418100+08:00[Asia/Shanghai],2024-05-25T22:39:01.047418100+08:00[Asia/Shanghai]
#            - Cookie=username, rts
#            - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.rents.com,**.anotherhost.org
#            - Query=green
            - RemoteAddr=192.168.0.1/24 # 外部访问我的IP限制，最大跨度不超过32，目前是1~24他们是CIDR表示法
            - Method=GET,POST # 配置某个请求地址，只能用Get/Post方法访问，方法限制
            - My=diamond
logging:
  level:
    root: info
    com:
      rts: debug
  file:
    name: "D:/rts_springcloud_study/cloud_gateway9527.log"
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger- %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger- %msg%n"