server:
  port: 8401

spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080 # 配置Sentinel dashboard 控制台服务地址
        port: 8719 # 默认8719
      web-context-unify: false # controller层的方法对service层调用不认为是同一个根链路
      datasource: # Sentinel 持久化配置
        xiyue1: # 就是自定义Key，也可以叫做限流类型等等
          nacos:
            server-addr: localhost:8848 # nacos地址
            dataId: ${spring.application.name} # 就是nacos配置里面的
            group-id: DEFAULT_GROUP # 就是nacos配置里面的
            data-type: json # 就是nacos配置里面的
            rule-type: flow # 此处为流控规则，具体类型见 com.alibaba.cloud.sentinel.datasource.RuleType
        xiyue3: # 就是自定义Key，也可以叫做限流类型等等
          nacos:
            server-addr: localhost:8848 # nacos地址
            dataId: flow # 就是nacos配置里面的
            group-id: DEFAULT_GROUP # 就是nacos配置里面的
            data-type: json # 就是nacos配置里面的
            rule-type: flow # 此处为流控规则，具体类型见 com.alibaba.cloud.sentinel.datasource.RuleType
        xiyue2: # 就是自定义Key，也可以叫做限流类型等等
          nacos:
            server-addr: localhost:8848 # nacos地址
            dataId: degrade # 就是nacos配置里面的
            group-id: DEFAULT_GROUP # 就是nacos配置里面的
            data-type: json # 就是nacos配置里面的
            rule-type: degrade # 此处为熔断规则，具体类型见 com.alibaba.cloud.sentinel.datasource.RuleType